# Task to Install Third Party pip Packages
#
# Inputs:
#   * app-git: GitHub repo with an Application Source
#   * OW_APP_PYTHON_VERSION: any specific Node Version you want to pull, default is "python"
#   * OW_APP_PATH: path to application directory within the GitHub repo, default is ""
#
#
# Application source is cloned under /workspace/<resource-name> by default if targetPath is not specified.
#
# This task installs third party packages under /workspace/<resource-name>/<app_path>/
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-install-pip-packages
spec:
  workspaces:
    - name: openwhisk-workspace
  params:
    - name: OW_APP_PYTHON_VERSION
      default: "python"
      description: "Any specific Python version needed to compile/run application source on"
    - name: OW_APP_PATH
      default: ""
      description: "Relative or Absolute path to the application source"
  steps:
    - name: install-pip-packages
      image: $(params.OW_APP_PYTHON_VERSION)
      script: |
        #!/usr/bin/env bash
        set -xe
        echo $(params.OW_APP_PATH)
        if [ -z "$(params.OW_APP_PATH)" ]; then
          OW_APP_PATH=$(workspaces.openwhisk-workspace.path)/application/
        else
          OW_APP_PATH=$(workspaces.openwhisk-workspace.path)/application/$(params.OW_APP_PATH)
        fi
        echo $OW_APP_PATH
        cd $OW_APP_PATH
        apt update
        apt install -y python3-pip
        pip3 install virtualenv
        echo "Creating venv"
        virtualenv virtualenv
        source virtualenv/bin/activate
        echo "Starting to install pip Packages under $OW_APP_PATH"
        ls -d virtualenv/lib/python3.*/site-packages/* > virtualenv/site-packages.lst
        pip install -r requirements.txt
        if [ $? = 0 ]; then
          echo "Successfully finished installing pip Packages under $OW_APP_PATH"
        else
          echo "Failed to install pip Packages under $OW_APP_PATH"
        fi
